version: '2'

services:
    server_recheckmail:
        image: server_recheckmail
        ports:
            - "5000:5000"
        volumes:
            - ./:/code
        networks:
            - code-network
networks:
    code-network:
        driver: bridge
